# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-10 19:21
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('filer', '0010_auto_20180414_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cart item',
                'verbose_name_plural': 'Cart items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=60, verbose_name='Client name')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone number')),
                ('shipping_address', models.TextField(verbose_name='Delivery address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_unique_id', models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True, verbose_name='Order Id')),
                ('products', models.TextField(blank=True, null=True)),
                ('total_weight', models.IntegerField(default=50)),
                ('delivery_price', models.FloatField(default=Decimal('25000'))),
                ('porter_work_price', models.FloatField(default=Decimal('0'))),
                ('products_price', models.FloatField(null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_time', models.DateTimeField(null=True)),
                ('need_porter', models.BooleanField(default=False)),
                ('state', models.IntegerField(blank=True, choices=[(0, 'Available'), (1, 'Awaiting Payment'), (2, 'Payment completed'), (3, 'Cancelled'), (4, 'Delivered'), (-1, 'In process')], default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('method', models.CharField(choices=[('uzcard', 'Uzcard'), ('payme', 'Payme'), ('cash_on_delivery', 'Cash on delivery')], default='uzcard', max_length=40, unique=True)),
                ('logo', filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentMethodTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(blank=True, null=True)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='order.PaymentMethod')),
            ],
            options={
                'verbose_name': 'payment method Translation',
                'db_table': 'order_paymentmethod_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Variation'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethodtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
